version: '3.3'

services:
  postgres:
    container_name: container_post_super
    image: postgres
    environment:
      POSTGRES_DB: "superK"
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"